import pygame
import random

GAME_NAME = '\t\t\t\t X GHOST \t\t\t\t'
MAP_WIDTH = 600
MAP_HEIGHT = 400

C_BLACK = (100,100,100)
C_RED = (255,0,0)
C_GREEN = (0,255,0)
C_BLUE = (0,0,255)

TXT_GAME_OVER = 'Game Over'
TXT_WINNER = '*5*% YOU WIN %*5*'
TXT_WELLCOME = 'STARTING GAME'

PLAYER_MAX_BULLETS = 5
ENEMY_MAX_BULLETS = 4

PLAYER_ACCELERATION_X = 0.2
PLAYER_ACCELERATION_Y = 0.2

DEFAULT_WIDTH = 20
DEFAULT_HEIGHT = 20

ENEMY_Y_SPEED = 3
ENEMY_X_SPEED = 3


SIZE_1 = 10
SIZE_2 = 20
SIZE_3 = 30

PLAYER_IMAGE = "ghost-idle.png"
FPS = 20  #GAME SPEED

ARIAL = 'Arial'
